name: bagep
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - r-vcfr
  - pandoc
  - r-argparse
  - r-heatmaply
  - python=3.6
  - fastp
  - snippy=4.6.0
  - iqtree
  - snakemake=6.12.1
  - centrifuge
  - krona
  - abricate
